
# version: "3.10"

services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reviews-frontend
    ports:
      - "3000:80"  # Maps port 3000 on your host to port 80 in the container
    restart: always
    depends_on:
      - web
    networks:
      - app-network_live

networks:
  app-network_live:
    external: true
