
services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reviews-frontend # container name 
    ports:
      - "3000:80" # Maps port 3000 on your host to port 80 in the container
    restart: always
