# Generated by Django 5.1.6 on 2025-03-05 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mobiles",
            fields=[
                (
                    "ean",
                    models.CharField(
                        help_text="Enter a 13-digit EAN (only numbers).",
                        max_length=13,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="EAN must be exactly 13 digits.",
                                regex="^\\d{13}$",
                            )
                        ],
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=500)),
                (
                    "marketers",
                    models.ManyToManyField(
                        related_name="marketed_mobiles", to="marketers.marketer"
                    ),
                ),
            ],
        ),
    ]
