# Generated by Django 5.1.6 on 2025-03-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mobiles",
            name="marketers",
        ),
    ]
