# Generated by Django 5.1.6 on 2025-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketers", "0001_initial"),
        ("mobiles", "0002_remove_mobiles_marketers"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobiles",
            name="marketers",
            field=models.ManyToManyField(
                blank=True, related_name="marketed_mobiles", to="marketers.marketer"
            ),
        ),
    ]
