# Generated by Django 5.1.7 on 2025-03-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_mobiles_marketers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
