# Generated by Django 5.1.7 on 2025-04-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_mobiles_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiles',
            name='name',
        ),
    ]
